In [1]:
from PIL import Image
from tqdm.auto import tqdm
import torch
from transformers import AutoModelForImageClassification, AutoImageProcessor


/Users/ravitiwari/llm-dev/assignment-app/env/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [10]:
model_path = "/Users/ravitiwari/llm-dev/assignment-app/model/vit-base"

In [11]:
from transformers import AutoModelForImageClassification, AutoImageProcessor

image_processor = AutoImageProcessor.from_pretrained(model_path)
modelfinetuned = AutoModelForImageClassification.from_pretrained(model_path)

In [13]:
#Data folder is not in this same directory
from datasets import load_dataset

data = load_dataset("imagefolder", data_dir="/Users/ravitiwari/llm-dev/assignment/data")

Resolving data files:   0%|          | 0/1106 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/150 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/300 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

In [14]:
test = data['test']

In [15]:
true = []
predicted = []
for i in tqdm(range(len(test))):
  encoding = image_processor(test[i]['image'].convert("RGB"), return_tensors="pt")
    # forward pass
  with torch.no_grad():
      outputs = modelfinetuned(**encoding)
      logits = outputs.logits
  predicted_class_idx = logits.argmax(-1).item()
  predicted.append(predicted_class_idx)
  true.append(test[i]['label'])

  0%|          | 0/300 [00:00<?, ?it/s]

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix

# Calculate accuracy
accuracy = accuracy_score(true, predicted)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Calculate confusion matrix
conf_matrix = confusion_matrix(true, predicted)
print("Confusion Matrix:")
print(conf_matrix)


Accuracy: 96.67%
Confusion Matrix:
[[100   0   0]
 [  0  99   1]
 [  7   2  91]]
